### ISSUE TITLE
Image uploads for wiki

### ISSUE THREAD

**Issue by rajpersram** [bcgov/cas-ciip-portal#1626]
Adding a new image here destined for the wiki as the recommended workaround.

![add a comment](https://user-images.githubusercontent.com/18739261/116136160-cd973780-a686-11eb-8421-5400176cad78.png)

**Comment by rajpersram** [comment]
![review-application-comments](https://user-images.githubusercontent.com/18739261/116157497-efea7e80-a6a1-11eb-80df-d2412557f53f.jpg)

**Comment by rajpersram** [comment]
![inline-help-icon](https://user-images.githubusercontent.com/18739261/116158209-1a890700-a6a3-11eb-8f3f-a305aa83945b.jpg)

**Comment by rajpersram** [comment]
![product-benchmark-link](https://user-images.githubusercontent.com/18739261/116159373-f8908400-a6a4-11eb-9fbd-a81b80fadd5d.jpg)

**Comment by rajpersram** [comment]
![admin-dashboard](https://user-images.githubusercontent.com/18739261/116160261-9173cf00-a6a6-11eb-8322-5693a07e517b.jpg)

**Comment by rajpersram** [comment]
![add-a-comment-anim](https://user-images.githubusercontent.com/18739261/116454768-32809800-a815-11eb-9c35-840591b9819e.gif)

**Comment by rajpersram** [comment]
![operation-access-request](https://user-images.githubusercontent.com/18739261/116624647-26700580-a8fd-11eb-89b5-695ffffe21b5.gif)

**Comment by rajpersram** [comment]
![tab-navigation](https://user-images.githubusercontent.com/18739261/116625031-d3e31900-a8fd-11eb-8c5e-a9d59834a359.gif)

**Comment by rajpersram** [comment]
![opened-tech-review](https://user-images.githubusercontent.com/18739261/118702076-51959880-b7c9-11eb-9ba0-508c11bd5a22.png)

**Comment by rajpersram** [comment]
![steps-to-apply-facility](https://user-images.githubusercontent.com/18739261/118727488-ae07b080-b7e7-11eb-8cd1-e5a0950c5fa0.png)

**Comment by rajpersram** [comment]
![ciip-application-tabs-2](https://user-images.githubusercontent.com/18739261/119034961-e3d1a400-b963-11eb-8ba7-1645dd4860a4.png)

**Comment by rajpersram** [comment]
![tab-navigation-example-2](https://user-images.githubusercontent.com/18739261/119035164-1f6c6e00-b964-11eb-8cc8-8606735dd3d0.gif)

**Comment by rajpersram** [comment]
![summary-page-comments](https://user-images.githubusercontent.com/18739261/119735528-5396d180-be31-11eb-94a8-cdced678b435.png)

**Comment by rajpersram** [comment]
![application-status-relation](https://user-images.githubusercontent.com/18739261/119863623-9c509800-bece-11eb-96e1-e761305723c6.jpg)

**Comment by rajpersram** [comment]
![naics-links-dead-end](https://user-images.githubusercontent.com/18739261/121261108-1d147a00-c867-11eb-932e-fc8bae4493fa.jpg)

**Comment by rajpersram** [comment]
![naics-add-optional](https://user-images.githubusercontent.com/18739261/121390743-85fd0000-c902-11eb-86e1-918b921bb98f.gif)

**Comment by rajpersram** [comment]
![naics-add-mandatory](https://user-images.githubusercontent.com/18739261/121396965-c0699b80-c908-11eb-967d-89610178bbb1.gif)

**Comment by matthieu-foucault** [comment]
This issue can be closed and still have images added to it. Closing it so that it does not appear in our backlog
