### ISSUE TITLE
As an administrator, I want to define the reporting years for which the CIIP configuration is valid

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1751]
As a reporter/analyst/admin, I want to have consistency across reporting years when product data (name, benchmark) change. See Miro board, 'NAICS - Products maintainability scratchpad'.

The set of features needed to prevent and manage the effects of deleting or archiving a NAICS code, product, or NAICS-product association.
 
•	With the current implementation, when a NAICS code, a product or a NAICS-product association gets deleted/archived, it will result in errors/warnings displayed in previous years’ applications that use these deleted/archived items, even though that was valid at the time.

**Comment by Dianadec** [comment]
(copied from Roadmap Miro) - Some of this work could be broken out (and have all the context written down) right away to ensure we can refine it in a future session. Involve SME in these discussions and understand the changes so it's not a surprise for anyone.
^ will need design as well before we can discuss implementation

**Comment by rdromey** [comment]
Tickets removed from epic, discussed with Pierre, good to close.
