### ISSUE TITLE
Onboard Stakeholders to GitHub

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1764]
Once setup on GH, we'll go over:

- [ ] ZenHub Board: what view to use
- [ ] What each column means
- [ ] Epic Prioritization
- [ ] how to view what we are working on in the current sprint/what will likely be demoed at the sprint review.
- [ ] how ZH relates to our roadmap

**Comment by Dianadec** [comment]
To clarify, in order for our gov stakeholders to access ZenHub, they'll just need to setup a GitHub account? Do they also need to be granted access to the BC Gov GH org? I'm happy to take this on just want to make sure I'm not missing a step. @matthieu-foucault

**Comment by matthieu-foucault** [comment]
I don't think they would need access to the org. We can test it out with our SME once she has an account

**Comment by Dianadec** [comment]
Confirmed that they just need to setup a GitHub ID then they can access our ZenHub board. Even as "view only" they can leave comments. So I don't think we need to do anything more than assisting with setting up a github ID as needed. I'll reach out to people next week to get them setup.
