### ISSUE TITLE
Hard runbook for catastrophic systems failure

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1774]
Discussed during release planning in April - see miro board for notes (GGRICS Roadmap Miro Board)

**Comment by Dianadec** [comment]
@matthieu-foucault can this be closed? I believe it was just the runbook ticket from last sprint left. I can't access youtrack right now though so let me know if I missed something. Thanks!

**Comment by rdromey** [comment]
Discussed with Pierre, good to close.
