### ISSUE TITLE
Fuel charge interface (ggircs app)

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1775]
As an admin
I want an interface that allows editing the fuel charge associated to each fuel
So when changes to the charges associated to individual fuels are applied I can easily make the change in CIIP

Background:
The fuel charges associated to each individual fuel originally went up at the same rate as the carbon tax's $/tCO2e rate. This stopped in 2020. The charges associated to each fuel are no longer linear and predictable. Having an interface where an admin can make the necessary changes on a fuel by fuel basis would  be a better solution than having developers continually updating hardcoded data based on changes in the CTA.

**Comment by dleard** [comment]
Closing this as the fuel interface work falls under the CIIP Features Epic #2034
