### ISSUE TITLE
As a logged in user, I want to see a modal prompting me to extend my session before I get logged out for being inactive

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1778]
## Description
See comments in GGIRCS-1799 for relevant discussion

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/193302a1-a3d2-4b2d-a9f8-7428ba7ba7e5)
Following GGIRCS-1799, sessions do not expire if the user is active (send requests to the server). However, if they remain idle, or are simply viewing a page without interacting with it, they will get redirected to the login-redirect page.
This feature will display a toast message prompting them to extend their session. Clicking on the toast message would send a request to the server, automatically refreshing the session.
Reference: https://youtrack.button.is/issue/GGIRCS-1799

## Acceptance Criteria
1) Given that I am logged in
    When I have not been active for 28 mins
    Then I should get a modal prompting me to extend my session

2) Given that I am seeing the modal
    When I click the 'remain active' button
    Then my session is extended for another 30 minutes

3) Given that I am seeing the modal
    When I click the 'logout' button
    Then my session ends immediately

## Development Checklist
- [ ] follow above wireframe
- [ ] have as a full overlay

**Comment by Dianadec** [comment]
@rajpersram the design in this card needs updating. Please review and add an example of a potential design so that we can estimate the work. Thanks!

**Comment by rajpersram** [comment]
Attached is the export for a session about to expire (changing the time frame as needed), and the message on the log-in page after they have been logged out.![CIIP Modal Messages.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/d18d9127-16ae-49f9-a26d-15c7665dd4e3)

[Miro CIIP Modal Message board here](https://miro.com/app/board/o9J_lS5yny0=/).

**Comment by matthieu-foucault** [comment]
We cannot display a message on the login page for technical reasons. There is already a message explaining the reason for logging out on a `login-redirect` page, so that does not need to be updated.

What would the `Continue` and `Exit` button do on the toast message? Should they be `Stay logged in` and `Log out` instead?
In planning/refinement, we had discussed it being a modal rather than a toast message, for greater visibility

**Comment by rajpersram** [comment]
Thanks @matthieu-foucault. Below is the modal window, following the BC Gov design constraints. Let me know what you think. ![CIIP Modal Messages 2.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/c2e73936-97db-4dad-8207-fb15961f75fe)

**Comment by matthieu-foucault** [comment]
Looks good to me!

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1778?planning-poker) with ZenHub @naomiaro @dleard @matthieu-foucault

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia for showing me how the modal works - our users will appreciate this new feature :)
