### ISSUE TITLE
As a developer, I want to analyze collected load testing data 

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1781]
...and identify slow queries (identify threshold for what slow means) or mutations, and find opportunities for optimization.

https://youtrack.button.is/issue/GGIRCS-2487

AC:
- [x] In the excel load test report, identify and document which page hosts which query
- [x] Create a short report that:
    - Describes very quickly the load testing methodology
    - Orders the queries by response time - slowest first
    - Confirm response time to qualify as a "slow" request is > 1s under load
- [x] Create user stories to speed up the "slow" ones
- [x] Identify if express server is a bottleneck (if it is the case, recommendation should be to add a HorizontalPodAutoscaler)

Stretch goal: (not included in estimate)
- [ ] Schedule a load testing presentation for the DevOps/Dev guild

**Comment by matthieu-foucault** [comment]
Added a load testing report in https://github.com/bcgov/cas-ciip-portal/wiki/2021-06-01-load-testing-analysis

**Comment by Maralsotoudehnia** [comment]
Nice work @matthieu-foucault and team! Do you want me to close this issue out?
