### ISSUE TITLE
Reusable UI Toolkit

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1787]
AC
Not using react bootstrap
Potential constraints (developers to elaborate)
Reach out to BC Design System team about contributing (what's the process?)

Reference links
https://github.com/button-inc/service-development-toolkit

**Comment by Dianadec** [comment]
Should this be in the ggircs repo instead?

**Comment by LindsayMacfarlane** [comment]
Backlog refinement September 7, 2021: @Dianadec - is this ticket still required?

**Comment by Dianadec** [comment]
@LindsayMacfarlane Only if it's relevant/helpful for the skeleton repo. I think that was my understanding the last time we brought this up as a team.

**Comment by matthieu-foucault** [comment]
This issue is not needed. The need for the UI toolkit will be captured in the acceptance criteria of the template app epic
