### ISSUE TITLE
Metabase cannot filter based on an enum type 

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ciip-portal#1799]
Figure out a permanent solution to dealing with enum types that are not recognized properly by metabase.
Issue on metabase github: https://github.com/metabase/metabase/issues/7092
A [comment](https://github.com/metabase/metabase/issues/7092#issuecomment-784591160) in the github issue suggests a possible workaround, which we can try.

I am thinking that maybe setting the database search path in the metabase connection (if possible) might fix the issue

Probability (1-5): 2

Effect (1-5): 3

**Comment by matthieu-foucault** [comment]
@Maralsotoudehnia  to review this, go to our [metabase development instance](https://cas-metabase-dev.apps.silver.devops.gov.bc.ca/), and you should be able to create a simple question that filters on an enum column, for instance the `Application Revision Status` table should be filterable on the `Application Revision Status` column:
 ![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/bf59971a-1376-43bc-90e2-0947a625896b)

**Comment by Maralsotoudehnia** [comment]
Works beautifully!
