### ISSUE TITLE
users should be automatically logged into CIIP if logged in in keycloak

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ciip-portal#1808]
Reporter: a reporter
Description: 
> I get an error saying my user name and email is already registered, I tried to login but of course I don’t know my password. I was able to reset my password but when I click on the link in my email it brings me to a page that says “you are already logged in” but when I go back to the CIIP main page it asks to login, but I still don’t know my password….

Additional information:
Discussion in GGIRCS-1801

**Comment by matthieu-foucault** [comment]
This issue was reported a year ago, and has not appeared since. Previous attempts at implementing a fix proved more complex than anticipated, so I'm closing this. We can reopen it if it is reported again.
