### ISSUE TITLE
CIIP website redesign

### ISSUE THREAD

**Issue by Maralsotoudehnia** [bcgov/cas-ciip-portal#1809]
Context: ICU are looking to review the design of the CIIP website and seeking UX support to do so.

Pre-Design
- [x] Conduct a discovery session with ICU team
- [x] Connect with ICU's tech specialist about layout constraints
- [x] Information architecture analysis [housed in Miro](https://miro.com/app/board/o9J_l6udsCY=/)

AC:

- [x] reach out to our SME at ICU and determine the scope of work
- [x] assess the [website](https://www2.gov.bc.ca/gov/content/environment/climate-change/industry/cleanbc-industrial-incentive-program)(s) in question
- [x] make recommendations for content redesign

**Comment by Maralsotoudehnia** [comment]
Context: ICU are looking to review the design of the CIIP website and seeking UX support to do so. 

AC: 
- reach out to our SME at ICU and determine the scope of work
- assess the website(s) in question
- make recommendations for redesign

**Comment by rajpersram** [comment]
Connecting with Hanna on Mon, June 28 to discuss.

**Comment by rajpersram** [comment]
Received what info we could from Andrea Klassen, who's in charge of the implementation of the page content in CMS Lite. Unfortunately her schedule is full for the week, while next week I will be away. Jaimie and I will take what Andrea's provided in terms of user feedback from the existing page, layout options in CMS Lite and hopefully some graphic asset libraries to come and forge on with the IA and prototyping to present to Hanna and Andrea next week.

**Comment by ChristopherShawFleming** [comment]
Meeting with Hanna today on this!

**Comment by LindsayMacfarlane** [comment]
Thank you so much Jamie for walking me through what's been done and what the next steps are to support on the website re-design.

Also, this is my first ticket as the new PO that I get to move to done :)
