### ISSUE TITLE
Test sites should be IDIR-protected

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ciip-portal#1821]
Migrated from GGIRCS-1717 and GGIRCS-2489

When someone tries to log in to -test with their IDIR, their email is already in the system (from -prod) and the email uniqueness validation throws.

To solve this, we can have an extra step right after we import the data from -prod:
update ggircs_portal.ciip_user set email_address = 'prod-' || email_address;

This renames people's emails from prod to "prod-<<email>>"

**Comment by rdromey** [comment]
No longer relevant as we are on the gold cluster.
