### ISSUE TITLE
As a reporter or analyst, I want to see the sum of facility emissions when viewing an application

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1844]
### Description

CAS would like to see the total emissions (minus CO2BioC emissions) for a facility when viewing an application. We already have a computed column that does this `application_revision_total_ciip_emissions`. We just need to display this data on the summary page.

### AC
As a CIIP analyst
When I am viewing an application summary
Then I can see the total CIIP (not CO2BioC) emissions

### Checklist
- [ ] The summary page displays the total ciip emissions

### Wireframes:
![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/089f99fc-4b3f-43cf-a26e-f0b867ac0c40)

**Comment by LindsayMacfarlane** [comment]
Backlog refinement (September 14, 2021): This may be a nice to have vs a priority.

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1844?planning-poker) with ZenHub @pbastia @matthieu-foucault

**Comment by matthieu-foucault** [comment]
The screenshot above is on the SWRS onsite emissions form. Do we want to add this info there as well? It would have to be refetched as the form is modified (so added to the mutation response)

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia! I tested in ciip dev. My UI looked a bit different than the wireframe included on this page, so I'm not 100% certain I tested in the correct location; however, I can confirm that the total on-site emissions are displayed under the subheading. 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/9865c393-a4a2-478d-91f7-0a5693914d38)

**Comment by pbastia** [comment]
@LindsayMacfarlane the wireframe only included the "On-Site emissions" tab, not the summary one, this is why there was a difference. The total can be found on both pages
