### ISSUE TITLE
More functional unit tests (dependent on a modular front-end refactor)

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1854]
Dependent on a frontend refactor to make components more modular and thus testable, it would be nice to have more functional tests that tell us why a test is failing.
Currently, all that our unit test failures tell us is not very logically helpful: "doesn't match last accepted snapshot"

We should perhaps consider functional unit tests as an acceptance criterion for some/many/most components in the frontend refactor?

Works toward addressing GGIRCS-1482.

**Comment by pbastia** [comment]
This was solved in the more modern tech stack of CIF but would be a huge undertaking for little value here.
