### ISSUE TITLE
Investigate use of cy.wait() in cypress specs

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1857]
cy.wait() instructions have been added in several places in the cypress specs. These were likely added (mostly by me) to address some local issues and are probably not universally needed or needed at all by CI.

Where to start:
I believe there are some that are needed. In the case of the email tests, a short wait is needed in order to ensure that the email has been received by mailhog before attempting to retrieve the message via the api & read the content.
Most if not all cy.wait() instructions in the before() / beforeEach() / or after() are good candidates for removal.

Acceptance:
All instances of cy.wait() should either be:
a) removed because they are not needed or
b) documented with a comment to indicate why it is being used.

**Comment by pbastia** [comment]
This is a lot of work for something not in active development, for not much gain.
