### ISSUE TITLE
ggircs_portal.certifier_url column issues

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1864]
deleted_by: user is vague, should explicity say that this is a foreign key to the ciip_user table
updated_by: user is vague, should explicity say that this is a foreign key to the ciip_user table
created_by: Creator is vague, should explicity say that this is a foreign key to the ciip_user table

since we're keeping the table the metadata should be updated to align with whatever comes out of the data modelling collaboration with IITD & CAS

**Comment by dleard** [comment]
certifier_url has been removed from the schema, dropping.
