### ISSUE TITLE
build a test docker image to run cas-ggircs CI

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1865]
Right now we have to add `libdbd-pg-perl` to each of the CI step's machines.
This task is to refactor into a common docker image that would be used across all CI steps

We want to get rid of these:
```
      - run:
          name: install libdbd-pg-perl
          command: |
            sudo apt-get update
            sudo apt-get install libdbd-pg-perl
```

**Comment by dleard** [comment]
No longer using CircleCI. Closing
