### ISSUE TITLE
Maintainable energy product relations

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1880]
Currently, several things rely on the energy products always being present, and in order from id 1-7 in the product table. These products are always generated this way via our deploy_data function and protected by a trigger on the table, so the risk of them being changed/deleted is minimal. But it would be good to find a more maintainable way to reference these products in the future.
Some ideas have been explored in a PR here: https://github.com/bcgov/cas-ciip-portal/pull/730

**Comment by pbastia** [comment]
The amount of work required to refactor this is not worth it, especially that this likely won't change within the CIIP lifecycle. There is a more manual update path if energy products were updated.
