### ISSUE TITLE
CIIP Portal: As a maintainer, I want to use the airflow-dag-trigger job (created in #91) to trigger the dag-fetch job.

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ciip-portal#1887]
Blocked: #91

#### Description:
We need to move the ciip DAGs from the aiflow repo to the ciip repo

#### Acceptance Criteria:
- the ciip dags are in the ciip repo
- on deploy, the airflow-dag-trigger job is called to trigger the dag-fetch from airflow.

**Comment by matthieu-foucault** [comment]
@pbastia @naomiaro I see we only support a single DAG file with the dag-fetch, which is okay. This does mean we'll have to refactor the code a bit with the next tasks. I would also suggest renaming the DAGs to prefix them with the repo name, as a convention to avoid name collision. This will also allow us to transition with both versions of the DAGs (the one in the CIIP repo and the one in the Airflow repo), and remove the airflow ones once CIIP is deployed to prod.

**Comment by pbastia** [comment]
@matthieu-foucault I see what you mean...there might be multiple files to pull as part of a single DAG even. Maybe it's worth allowing a list of paths from a single repo/ref?

**Comment by matthieu-foucault** [comment]
Ideally we would support the path to be a directory, but that would likely require using the github API. I think a single file is fine for now
