### ISSUE TITLE
Simplify frontend directory structure [frontend tech debt]

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1889]
We've been complaining for some time that the directory (+ filenaming, to a minor extent) organization of frontend components vs. containers seems a bit meaningless, as it splits up components that are otherwise closely related. We proposed that it could be simplified to something like the below, which is the sketchy example we came up with in the frontend tech debt meeting.

To be made **Ready**, this card needs a more specific outline of the folders and locations that would be changed, with a double check with developers that it's agreed upon. It might also be good to have some idea of where GGIRCS-2117 may take us (in terms of file organization) before actioning this.

![image.png](https://images.zenhubusercontent.com/5eab031d3b2d9c0616c10052/21091ee1-eb7c-42d9-b19b-09d224287624)

**Comment by pbastia** [comment]
pretty big code reorganisation for little value
