### ISSUE TITLE
sqitch-check-immutable-files.sh script should ensure that sqitch.plan lines that are deployed to prod are not modified

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1890]
As a developer, when I run .bin/sqitch-check-immutable-files.sh, 
I want to make sure that I did not modify a line of the sqitch.plan file that is above or including the last tag.

This is about the `sqitch.plan` file itself, not the sqitch changes it references. 
If a `sqitch.plan` line is changed, its hash, used as an id in the sqitch schema, will change, which will introduce unique index failures when attempting a `sqitch deploy` in test/prod

**Comment by dleard** [comment]
closing old card. This check is not needed. The current implementation of immutable-files is sufficient
