### ISSUE TITLE
map jwt realms to postgres roles

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1891]
Removing old TODO tag in `app/server/postgraphile/authenticationPgSettings.js:85`

  // TODOx: actually map jwt realms to postgres roles
  // @see https://www.postgresql.org/docs/current/default-roles.html
  // claims['role'] = 'pg_monitor';

**Comment by pbastia** [comment]
There is some kind of mapping in `groups.json`. Not sure what this issue is about anymore.
