### ISSUE TITLE
Organize + modularize server file

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1892]
`app/server/index.js` has gotten quite long and could be broken up by extracting thematic pieces out into modules. Your thoughts are welcome here.

Appropriate content for  a server index is usually related to configuration, connection and startup of various modules and middleware, such as the database, networking, etc. Ideally, thematic modules can do their own in-depth configuration and pass them back to the server index.

As example, some possible modules are:

- handling related to dev mode flags
- keycloak handling
- database setup and config
- custom routes can be extracted to a `app/server/routes/` folder and mounted on `/` with data injection:
```
const routes = require("./routes/index")(dataHelpers);
app.use("/", routes);
```

**Comment by pbastia** [comment]
This was done as part of the KC Gold migration
