### ISSUE TITLE
jwt token type

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1902]
from deploy/types/jwt_token.sql
Not sure if this is an actual TODO or should be converted into documentation? @wenzowski

-- TODO: should be conformant with https://tools.ietf.org/html/rfc7519
-- Sample payload from Keycloak via IDIR provider
--  { jti: 'a090bc6c-dccd-4e55-857c-eb1a7bda2034',
--    exp: 1571273650,
--    nbf: 0,
--    iat: 1571273350,
--    iss: 'https://sso-dev.pathfinder.gov.bc.ca/auth/realms/pisrwwhx',
--    aud: 'cas-ciip-portal',
--    sub: '46d2dafb-f48f-4782-838c-37d6a3e2d34a',
--    typ: 'ID',
--    azp: 'cas-ciip-portal',
--    auth_time: 1571272904,
--    session_state: 'e0444b80-0ce0-4ea6-a3e6-5a227122af3c',
--    acr: '0',
--    broker_session_id: 'idir.93e47291-35a5-43df-b184-5fceea1aee29',
--    email_verified: false,
--    name: 
--    preferred_username: 
--    given_name: 
--    family_name:
--    email:

**Comment by wenzowski** [comment]
The [ggircs_portal.jwt_token](https://github.com/bcgov/cas-ciip-portal/blob/develop/schema/deploy/types/jwt_token.sql) type controls the claims interface per the [Graphile JWT Guide](https://www.graphile.org/postgraphile/jwt-guide/). Where possible, the attributes of the claim should follow the [RFC 7519 naming conventions](https://datatracker.ietf.org/doc/html/rfc7519) not the keycloak naming conventions to ensure portability with other identity providers (other IdP). Ideally the keycloak payload from the current keycloak version would be cast to RFC 7519 at the boundary layer, as would any differently formed payload from either a future breaking release of keycloak or a replacement IdP technology.

**Comment by pbastia** [comment]
There is little value in RFC7519 compliance this close to CIIP end of lifecycle
