### ISSUE TITLE
As an analyst, I want to see the data and incentive details of a ciip app in MB dashboard

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1910]
#### Description:
Create a MB dashboard with a filter for the application ID
when entering an app ID the dash should show the administrative data for the latest version of that application.
#### Acceptance Criteria:
- [x] MB Dashboard contains filter for app ID
- [x] Include in table:
- carbon tax
- incentive ratio, 
- incentive payment, 
- maximum incentive payment
- total ciip emissions
- admin data
- actual carbon tax rate
- [x] Tracking sheet data (combination of some of the above data for download into the CAS tracking sheet)

test: Get ICU Unit Head to validate that the data is accurate (matches spreadsheet)

**Comment by pbastia** [comment]
Reference screenshots
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/87901b0b-4f14-4c83-99ca-a0bb032a26a5)

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/6e7c1416-6da3-49bc-b9da-ea8fccba30a8)

**Comment by Maralsotoudehnia** [comment]
Nice work @dleard! I see the tracking sheet is in there, too, so is it all right that I checked it off the list above? Once we get confirmation from our users, I'll re-review/approve accordingly.
