### ISSUE TITLE
As an Analyst, I want to validate that liquids are not reported for venting and flaring

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1915]
#### Description:
The CIIP app does not restrict which fuels can be reported in the venting and flaring categories. This validation is required to verify that the reporter only reported acceptable fuels. It is in MB because the list of acceptable fuels is subject to change. (initially it was only natural gas but more might be allowed)

#### Acceptance Criteria:
- [x] Validation dashboard (#1910) has a widget that ensures that only the acceptable fuels are reported for flaring and venting.
- [x] list of acceptable fuels is defined in a question (see validation parameters collection)

**Comment by Dianadec** [comment]
this is a comment

**Comment by hannavovk** [comment]
Only gaseous fuels are acceptable in flaring or venting categories. These are listed below (incl. fuel ID) and can also be found referenced in cell E90 or F89 in the Fuel Check tab of the CIIP Review Tool.
 
While the initial intent was to allow only natural gas to be reported as a fuel for venting and flaring (this is what is described in the sector guidance), as we weren't able to restrict the fuels that applicants can select in the Web App (and they are using all sorts of fuels), we will allow other fuels as long as they are gases. Liquid fuels are not acceptable. 

Acceptable fuels (+ fuel ID):
- Acetylene (1)
- Biogas (captured methane) (8)
- CNCGs (16)
- Coke Oven Gas (19)
- Digester Gas (25)
- DNCGs (29)
- Field Gas (36)
- Field gas or process vent gas (35)
- Landfill Gas (42)
- Natural Gas (53)
- Nitrous Oxide (54)
- Refinery Fuel Gas (63)
- RFG - Mix Drum (66)
- RFG - Reformer Gas (67)
- SMR PSA Tail Gas (69)
- Still Gas - Refineries (73)
- Tail Gas (76)

**Comment by pbastia** [comment]
The first part of this question was addressed as part of #1914
