### ISSUE TITLE
Training placeholder

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1922]

**Comment by pbastia** [comment]
@dleard is there anything you can remember that we wanted to do, on the topic of metabase training for CIIP? Otherwise, feel free to close this card

**Comment by LindsayMacfarlane** [comment]
@Dianadec - I think we can close this one? I created a new ticket to capture the training that is taking place next sprint. Thoughts?

**Comment by LindsayMacfarlane** [comment]
This ticket is now a duplicate. Closing.
