### ISSUE TITLE
CIIP website redesign - Design

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1936]
This AC was pulled out from the initial [CIIP website redesign card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1809)

**The Design:**
- [x] Get Hanna's feedback
- [x] Lo-fi wireframe

**AC:**
- [x] Create designs
- [x] Share low-fi designs with ICU team

**Notes:**
- Miro board with designs: https://miro.com/app/board/o9J_l6udsCY=/

**Comment by matthieu-foucault** [comment]
@rajpersram to check in with Hanna next week

**Comment by Dianadec** [comment]
@rajpersram I pulled this into the sprint backlog since it looks like the first AC could be done this week (getting hanna's feedback) as per our conversation during standup. cc @jaimiebutton

**Comment by Dianadec** [comment]
Any additional feedback after Clean Growth ED reviews designs will go into another card as additional work.

**Comment by rajpersram** [comment]
Hanna and Andrea provided feedback, mostly around what's possible in CMS Lite. Passing it off to Andrea for implementation.

**Comment by LindsayMacfarlane** [comment]
Designs look great @rajpersram! Also great to see the collaboration of teams to make public information more user friendly and accessible.
