### ISSUE TITLE
ciip_production view does not return products comments

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ciip-portal#1940]
Describe the Bug:

the `ciip_production` view attempts to return the contents of a `comments` property at the root of the `form_result`. However, the `comments` property is contained in each array item, and should be retrieved in the same manner as the other production fields, i.e.
```
(x.production_data ->> 'comments')::varchar(10000) as comments
```

This bug prevents analysts from easily seeing comments in Metabase. Workarounds include looking at the application in the CIIP web app, and looking at the `form_results` table (containing the form data in JSON format).

Probability (1-5): 4

Effect (1-5): 2

**Comment by LindsayMacfarlane** [comment]
Thank you so much @dleard for walking me through the solution and what was implemented to fix this bug. 

Approved.
