### ISSUE TITLE
ciip incentive per product returns wrong products emission intensity instead of 0

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ciip-portal#1948]
## Description

Some products with a product amount and emissions amount of 0 are showing an emission intensity other than 0 in the results of the `application_revision_ciip_incentive`

The emission intensity returned is the emission intensity of another product in the same application.

The issue is [here](https://github.com/bcgov/cas-ciip-portal/blob/25345a7536fc85aef36d0342f3336ac88fca7988/schema/deploy/computed_columns/application_revision_ciip_incentive.sql#L182)

```sql
if (product.product_amount = 0) then
  intensity_range = 0;
else
```
should be replaced by 
```sql
if (product.product_amount = 0) then
  intensity_range = 0;
  em_intensity = 0;
else
```

While we're editing this function, this `intensity_range` variable should just be replaced with `incentive_ratio`. Its current name does not make sense and there is no need for a separate variable.

**Comment by LindsayMacfarlane** [comment]
Thank you so much @dleard for walking me through the solution and what was implemented to fix this bug. 

Approved.
