### ISSUE TITLE
As a user, I want all interactions with the website to extend my sessions, so that I don't get logged out

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1964]
#### Description:
As an analyst adding a comment does not trigger a network request. This causes them to be logged out because they are considered as inactive. Any click on the page or scrolling event should extend the session. 

- as per feedback from CIIP Analysts reviewing applications and leaving comments, realizing comments are not being saved and losing work.

#### Acceptance Criteria:
- [x]  throttle requests to only bump the session every 10 seconds
- [x] listen to click events (click, key press and scroll events)
- [x] send request to extend-session end-point whenever the events are triggered

**Comment by Dianadec** [comment]
Need to add tech details. This should be in the skeleton app.

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia for walking me through the work that was completed for this ticket. Much appreciate it.
