### ISSUE TITLE
Write tests to ensure that applicants can edit applications from a previous reporting year

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ciip-portal#1974]
#### Describe the task

... and that a version 1 application that would have been left in draft from a previous reporting year cannot be submitted

#### Acceptance Criteria

- [x] Database tests (pgTap):
   - Database allows for editing submitted applications from previous years
   - Database does not allow submitting a previous year's application in version 1 that was not submitted (in draft status)
- [x] Unit tests (jest)
   - The 'revise application' button appears for an application that was submitted in a previous year & has been 
     changed to 'changes requested' status.
   - The 'submit application' button does not appear for an application that was started in a previous year but was not 
      submitted.

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1974?planning-poker) with ZenHub @dleard @matthieu-foucault
