### ISSUE TITLE
As an incentive analyst, I want the CIIP views in Metabase to only display the latest submitted revision of an application, so that I can easily see the status of the CIIP program

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ciip-portal#1975]
#### Description:

4 views: ciip_admin, ciip_emission, ciip_fuel, ciip_production

 - ~~the default view should only show the data for the latest submitted revisions~~
 - ~~rename the existing views that shows all versions (including draft revisions) (e.g `ciip_admin_all_versions`)~~

Update from December 13th prioritization meeting:

-Instead of changing the underlying database views or creating new ones with filters, let's create questions in metabase that use the current views and filter by latest version.
- Add these 4 questions into their own collection to increase visibility and make it easy to find them.
- Advise CIIP users where to find this collection / set of new questions

**Comment by Sriram-pc** [comment]
to be discussed with Hanna; Backlog refinement

**Comment by LindsayMacfarlane** [comment]
Prioritization session notes: this issue can potentially be solved by filtering out view directly in Metabase (vs changing the views).

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1975?planning-poker) with Zenhub @BCerki @gurjmatharu @mikevespi @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by Dianadec** [comment]
@pbastia to add a card to cover his question above.

**Comment by Dianadec** [comment]
No estimate needed for this card.
