### ISSUE TITLE
Identify CIIP Feature Requests

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ciip-portal#1980]
The GGIRCS team will have some time in the fall while undergoing the CIF Discovery phase - giving us time to work on smaller CIIP feature requests & bug fixes.

** Acceptance Criteria: **
- [x] Nudge CIIP team to review icebox items
- [x] @LindsayMacfarlane to see where CIIP team is at in icebox review process (Email sent Oct 19, Nov 2)
- [x] Design workshop (Feature Planning - 2021/2022 Miro Board) to rank items based on value & feasibility
- [x] Ram/Lindsay to set up meeting times for discussion
- [x] Conduct first workshop

** Notes: **
- Diana provided list of icebox items for review
- HV (Sept 22): Lessons learned meeting for CIIP is underway, so estimate review of icebox in the next couple of weeks; would like workshop/meeting with team to go through priorities

**Workshop Goals:**
- Create and prioritize shortlist of potential changes to CIIP app
- Use information from Icebox, Hanna's email to Lindsay & Matthieu, the results of CIIP team's debrief, and new feedback

**Comment by LindsayMacfarlane** [comment]
Sprint Planning (October 29, 2021): Team doesn't want to lose this and wants to keep in sprint.

**Comment by LindsayMacfarlane** [comment]
Well planned and designed session @jaimiebutton. There was a lot of great discussions...so much so, in the future, we could probably have a longer session ;)
