### ISSUE TITLE
As an Incentive administrator I can define which fuels can be reported for each emission category so that those fuels will be the ones shown to the industrial reporters when they apply

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-ciip-portal#1985]
#### Description:
Applicants should report flaring and venting using the Natural Gas fuel. The guidance states this, but it was ignored by many and we received many applications with various other fuels reporting under flaring and venting. 

##### Design to replicate
The screenshot below is *not* what should be implemented for this feature, but a similar configuration UI (the `admin/product-naics` page) that can be replicated and tweaked to fit this user story. 
Specifically:

- the list on the left should be the list of fuels, instead of NAICS codes
- instead of a search box for the list of product, there should be a drop-down list that allows to add an emission category.
- instead of the two options to add an entry, there should only be one "add" button (no such thing as a mandatory emission category).

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/588a1283-4415-4171-bb8d-c5fdd4e01894)

#### Acceptance Criteria:

- A `fuel_emission_category` table exists. This table has a compound PK of (fuel_id, emission_category_id) and the timestamp columns generated by the `upsert_timestamp_columns` function.
- The `fuel_emission_category` table has select, insert and update permissions for admins, and select for reporters and analysts.
- The `admin/fuel-emission-category` page allows administrators to add emission categories to fuels and to mark them as "deleted", following the UI described above
- The `FormConfiguration` component has a link to the `admin/fuel-emission-category` page

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1985?planning-poker) with ZenHub @dleard @naomiaro @pbastia

**Comment by suhafa** [comment]
Notes from [CIIP Prioritization Session](https://miro.com/app/board/o9J_llLjTeI=/): "We have a template for this type of UI (e.g., NAICS code). We can duplicate/reuse this template; however, it will require new database (?)"

**Comment by LindsayMacfarlane** [comment]
Ticket needs to be reviewed based on follow up conversations. Given time and priorities, we can now approach by getting a list from CIIP and then hardcoding the values vs building a new UI.

**Comment by dleard** [comment]
Closing this issue. This ticket has been replaced by #2145 after December 2022 discussion with CAS on priorities
