### ISSUE TITLE
As a reporter, I want to see the validation checking that reporting fuels and emission categories for carbon taxed emission categories only, so that I am reporting correctly

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-ciip-portal#1987]
#### Description:
One of the validations in the CIIP Web App is to check whether fuels have been reported in all reported emissions categories. However, this check should not apply to the fugitive emissions category as the fuels in this category are not taxed and do not need to be reported. We had many applicants contact us confused about the warning message they were seeing.    

#### Acceptance Criteria:
* Given that I am logged in as a reporter and I reported an emission amount in a non-carbon-taxed (e.g. fugitive, industrial process, see `emission_category` table) category, but no fuel in that category
When I navigate to the summary page
Then I do not see a warning related to fuels and emissions categories not matching
* Given that I am logged in as a reporter and I reported a fuel in a non-carbon-taxed category, but no emission amount in that category
When I navigate to the summary page
Then I do not see a warning related to fuels and emissions categories not matching

#### Checklist:
- [x] Update emission_category_missing_fuel to only include carbon taxed emission categories

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1987?planning-poker) with ZenHub @dleard @naomiaro @pbastia
