### ISSUE TITLE
As a reporter, I do not want to see a warning if I reported a CIIP product that does not require a product amount , so that I do not see a warning that cannot be fixed

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-ciip-portal#1988]
#### Description:
When a product is reported which doesn’t require the production amount to be reported or the production amount is equal to zero, but emission amount is greater than zero  the user receives a validation warning message. This is a false flag as they are not asked to report production. The validation is meant to check whether at least one appropriate product is reported, but the product itself might not require a production amount to be reported, such as the ‘Oil & Gas: other’ product. 

#### Acceptance Criteria:
* Given that I am logged in as a reporter and I reported a single product, configured with `requiresProductionAmount: false`
When I am navigating to the summary page
Then I do not see a warning saying that no products are reported

#### Checklist:
- [ ] Update no_reported_ciip_product so that it allows either products that have an amount greater than zero or where products do not require a production amount

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1988?planning-poker) with ZenHub @dleard @naomiaro @pbastia
