### ISSUE TITLE
CIIP pods should wait for sqitch migrations before starting

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ciip-portal#1998]
Describe the Bug:

With database migrations running during the helm release, as opposed to running as a pre-update hook, there is a risk that the application server starts before the database changes are applied. When database changes update the schema (i.e. a table, function or type signature is modified), this would result in posgraphile performing its introspection on the old schema, and any new change would not be propagated to the graphql API (e.g. a new column would not be available).

To solve this, the application pod should wait for the sqitch deployment to complete its migration, using an [init container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/).

Probability (1-5): 3

Effect (1-5): 5

**Comment by LindsayMacfarlane** [comment]
Accepted by Dev. No PO testing required.
