### ISSUE TITLE
Reverting a 2019 application decision creates extraneous review steps

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2019]
Describe the Bug:

When we created the concept of "review steps" for the 2020 application reporting year, we migrated comments to belong to a specific step (ie: administrative or technical). Since comments made in 2019 were not done this way, we grouped them all into a single legacy 'application review' step.

When a new application review is created, it is created with the two (administrative / technical steps). When re-reviewing a 2019 application, the two new review steps are erroneously created instead of the singleton. When an analyst tries to add a comment to these steps they get a relay error because the relay store does not have all the necessary comment-reviewStep connection data until a hard reload is done.

To fix:
The error from they relay store is a symptom, not the cause. The database trigger that creates new review steps should be fixed to not create the newer review steps for older applications & should introspect what review steps were used previously for the application being reviewed. This is somewhat similar to some work that was done regarding creating a new application revision for an older application and choosing what form_json to use in that case.
Work on that issue was done here: https://github.com/bcgov/cas-ciip-portal/pull/1979 mostly in `create_application_revision_mutation_chain`

Probability (1-5): 3

Effect (1-5): 1

Steps to reproduce the behaviour:

- as an analyst or admin open an application from the 2019 reporting year & notice that there is one review step: `application review`
- revert a decision on an application from the 2019 reporting year & notice that there are now 3 review steps.
- attempt to add a comment to the administrative or technical review step & the error modal will pop up.

**Comment by LindsayMacfarlane** [comment]
Thank you @dleard for walking me through the bug and solution that has been implemented.
