### ISSUE TITLE
Keycloak never logs out because the modal creates new tokens

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2026]
We were using keycloak.getGrant() to retrieve the remaining time until a token expires, but getGrant() calls ensureFreshness() and creates a new token set. This means the token is always refreshed when we ask how much time is left on the token.

Fix Ideas:

- The SessionTimeOutHandler.tsx component can't call the '/session-idle-remaining-time' to determine how much time is left on the token (because that creates new tokens).
- The SessionTimeOutHandler.tsx component useEffect should probably have two timeouts, one to show the modal and one to logout the user.
- The SessionTimeOutHandler.tsx component should check that it should in fact logout, in case the sessions was extended elsewhere.
- The SessionRefresher.tsx component should call  '/session-idle-remaining-time' on keypress / keydown / scroll?
- keycloak functions can possibly be extended?

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia !
