### ISSUE TITLE
Prioritize CIIP Feature Requests

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ciip-portal#2029]
This ticket follows [#1980 (Identify Feature Requests)](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1980) and [#100 (Prepare for Part 2)](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/100).

Acceptance Criteria:
- [x] Conduct Feature Request Part 2 session on Nov. 25
- [x] Fill in values in the Feature Matrix using rankings from session
- [x] Collectively decide on features to work on

**Comment by jaimiebutton** [comment]
Transferred :)

**Comment by LindsayMacfarlane** [comment]
Nice work @jaimiebutton ! The CIIP team really appreciated the two day approach and how our teams worked collaboratively to determine solutions. I also really enjoyed the prioritization activities and making sure our teams are aligned on approach and expectations.
