### ISSUE TITLE
Prepare for CIIP Feature Session Part 2

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ciip-portal#2030]
This ticket follows [#1980 (Identify CIIP Feature Requests)](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1980) and describes the work to be done before the second CIIP Feature Request session on Thursday, Nov. 25.

Acceptance Criteria:
- [x] Fill in Effort & Urgency values in Feature Matrix
- [x] Adjust boards for next session
- [x] Schedule time with GGIRCS team to align on feature effort before second session

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
