### ISSUE TITLE
As a CIIP analyst, I want to see the incentive ratios rounded off to FOUR digits after decimal.

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-ciip-portal#2033]
### Description:
The incentive calculators provided by CAS are the source of truth for the Incentive ratio. They round the ratio to two digits after decimal, so our application needs to align with that.

### Acceptance Criteria:
- [ ] Given I am on the incentive calculator
       When I see the incentive ratios
       The ratio should be rounded off to **four** digits after decimal.
- [ ] Given I am on the incentive calculator
       When I see the CIIP incentive amount (in CAD)
       Its calculation should be using an incentive ratio rounded off to **four** digits after decimal.

### Development Checklist

- [ ] This likely only requires a rework of the `computed_columns/application_revision_ciip_incentive` sqitch change, and rounding the incentive ratio [when it is calculated](https://github.com/bcgov/cas-ciip-portal/blob/8eb4a75b695b1fb489d5acc51cb0b52d8e8eaa4c/schema/deploy/computed_columns/application_revision_ciip_incentive.sql#L193)
- [ ] database tests need to be written/updated to ensure that rounding occurs

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/2033?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by LindsayMacfarlane** [comment]
Thanks for the demo @dleard and for following up with CIIP for additional testing!

**Comment by dleard** [comment]
Moving this back into 'in progress'. There was a misunderstanding in the ask. The actual outcome is this card should be to round to 4 decimal places. (the 2 decimal place ask was made with the ratio as a percentage in mind)
