### ISSUE TITLE
As a developer, I want to be able to define the fuels incremental tax baseline, i.e. the $30/tonnes rate, per reporting year

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-ciip-portal#2035]
Description:
The anticipated change is a methodology change for calculation of carbon tax for some fuels.

This means that the baseline (previously assumed to be the pre-2017 rate) may be different depending on the reporting period. 
This means that in the CIIP database, we need a new table containing the baseline rate for each carbon tax act fuel and each reporting period. If unspecified, the baseline would default to the current behavior (pre-2017 rate).

The data for the 2021 Incremental Carbon Tax rates is available in Scrum Team Channel.

[2021 Incremental CT Rate 2021-11-25](https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EYQazr7tmchEkvvG9hSrANcBSgmknMmixzNwc5yf5BVrig?e=8bFdFr)

This feature would add the database entities, prepopulated with the data mentioned above, and alter the calculation method. Any UI change would be done in #2048

#### Acceptance Criteria:
- The ciip database has a `ggircs_portal.incremental_fuel_charge_baseline` table with
  - A `carbon_tax_act_fuel_type_id` (which is effectively a foreign key to the `swrs.carbon_tax_act_fuel.id` column but should *not* be defined as such, as the `swrs` schema is managed separately, and will eventually be either accessed via an API or a foreign data wrapper).
  - A `start_reporting_period` and `end_reporting_period` column
  - A `fuel_charge_baseline` column
  - A `comments` column

- The `ggircs_portal.incremental_fuel_charge_baseline` table is pre-populated with the data provided by CAS
- The `ggircs_portal.application_revision_carbon_tax` is updated so that
   - It uses the baseline defined in `incremental_fuel_charge_baseline` for the application's reporting year, if defined
   - It keeps the existing behavior if no `incremental_fuel_charge_baseline` is defined (default to the 2018-03-31 rate)
- The carbon tax calculation diagram needs to be updated: Refer MiroBoard: Carbon-Tax Calculator diagram

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/2035?planning-poker) with ZenHub @AlexZorkin @pbastia

**Comment by LindsayMacfarlane** [comment]
Thanks for the demo @dleard :)
