### ISSUE TITLE
Review and update as needed fuel mapping table to include newest changes from SWRS

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-ciip-portal#2036]
Concerns: Needed fuel mapping changes may not be known until affected reports are received, so we can't really schedule this work?
double check that the combustible waste fuels are mapped properly

#### Acceptance Criteria:
* Option - use Ghirken:
Given
When
Then
* [Other AC]
* [Other AC]
* [Other AC]
* Meets the DOD

**Comment by matthieu-foucault** [comment]
Not much we can do here until there is an actual change in the SWRS fuels
