### ISSUE TITLE
As a CIIP analyst, I don't want to received an application submission in the GHGregulator shared inbox, so that I'm not distracted by them

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-ciip-portal#2039]
#### Describe the task
We use graphile-worker to schedule the sending of automated emails.
- graphile-worker is set up to listen in our app/server/index.js file (no action needed here)
- We have a graphile_worker_job_definer sql function in schema/deploy/database_functions that sends the data to the graphile worker (also no action needed here).
- We have a run_graphile_worker_job sql function in schema/deploy/trigger_functions/ that defines some parameters for the sendMail task. This function should be reworked to remove the case when an application is submitted and sends the `notify_admin_submitted` notification.
- We have some pre-defined templates in the app/server/emailTemplates directory that defines the content of what graphile-worker sends (in this directory we can remove `notifyAdminApplicationSubmitted`
- We also have a handler in app/server/tasks/sendMail.js. The corresponding block of code for the case `notify_admin_submitted` can be removed

#### Acceptance Criteria

- [x] rework `schema/deploy/trigger_functions/run_graphile_worker_job` to remove the block that sends the `notify_admin_submitted` email when an application's status is changed to submitted
- [x] remove the `app/server/emailTemplates/notifyAdminApplicationSubmitted` file from the templates
- [x] update the `app/server/tasks/sendMail` file to remove the case block for `notify_admin_submitted`
- [ ] update tests

#### Additional context

This issue could be worked around with an outlook inbox filter.

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/2039?planning-poker) with Zenhub @BCerki @gurjmatharu @mikevespi @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by LindsayMacfarlane** [comment]
Any recommendations on how I can test this one? Happy to punt over to the program area :)
