### ISSUE TITLE
As a CIIP admin, I want to define the CTA fuels incremental tax baseline, so that I can alter the CIIP incentive calculation

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ciip-portal#2048]
#### Description:

**update from December 13th prioritization meeting:**
The lifespan of this feature would be 2 years & these baselines only change once per year. 
As a result, this card is no longer needed. & can be replaced with a task to get the updated baselines from CAS & update the `incremental_fuel_charge_baseline` table with new values.

The incentive calculation uses a baseline value from the `incremental_fuel_charge_baseline` table that aligns with the federal rates. The table has this shape:

` id integer,
  carbon_tax_act_fuel_type_id integer,
  start_reporting_period integer,
  end_reporting_period integer,
  fuel_charge_baseline numeric,
  comment varchar(100000)`

The CIIP admin should be able to view and define the fuel_charge and the dates that fuel_charge is valid for each carbon taxed fuel type. This means they should be able to edit the currently valid data & add new fuel charge / period data for a CTA fuel type.

#### Acceptance Criteria:
Given I am logged into the CIIP app as an admin
When I am on the admin dashboard page
Then there is an `edit fuel charge baselines` option in the dashboard that directs me to the baselines management page

Given I am logged into the CIIP app as an admin
When I visit the baselines management page
Then I can see a list of CTA fuel types, their current baselines & valid dates

Given I am on the baselines management page
When I need to change the fuel charge for a CTA fuel type
Then there is an option to change the fuel charge

Given I am on the baselines management page
When I need to change the valid reporting years for a CTA fuel type & fuel charge
Then there is an option to change the reporting years

Given I am on the baselines management page
When I need to add context to a CTA fuel type / fuel_charge
Then there is a place to add a comment relating to that fuel charge

Given I am on the baselines management page
When I need to add a new baseline fuel charge value and valid reporting years for that charge
Then there is a UI to add a new baseline & period to a CTA fuel type

Development Checklist
* [ ] There is a `baseline-management` page
* [ ] The baseline management page can be accessed via the admin dashboard
* [ ] The page shows a list of CTA fuel types, their current baseline & the years this baseline is valid
* [ ] The list shows if there is a comment attached to that baseline
* [ ] The baseline fuel charge can be edited
* [ ] The reporting years that the baseline fuel charge is valid can be edited
* [ ] Edited valid years cannot overlap with another period where a baseline fuel charge relating to that fuel type is valid
* [ ] The baseline fuel charge & period can have a comment added
* [ ] A new baseline fuel charge with valid years can be added
* [ ] The reporting years that a new baseline fuel charge is valid for cannot overlap with any other baselines for that fuel type
* Meets the DOD

**Comment by LindsayMacfarlane** [comment]
Prioritization discussion notes: Given the length of this features lifespan, the most effective way to implement this ticket would be to make the updates manually (vs implementing new UI). CIIP team can provide us with the updated changes.

**Comment by dleard** [comment]
superceded by #2134. Closing this issue
