### ISSUE TITLE
get_swrs_facility_data should not use deprecated swrs.facility_details view

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2061]
Describe the Bug:
The get_swrs_facility_data function should not use swrs.facility_details. It has been deprecated since it was pretty ineffecient. The data that it is retrieving should be easily retrievable without using that view.

This bug is blocking deployment, it fails because it is looking for a view in swrs that has been removed.

Probability (1-5): 5

Effect (1-5): 5

**Comment by matthieu-foucault** [comment]
@dleard  putting back to in progress, I think you forgot to remove this a the beginning of the function:

```
if exists (
        select 1
        from   information_schema.views
        where  table_schema = 'swrs'
        and    table_name = 'facility_details'
      )
```
