### ISSUE TITLE
As a CIIP admin, I want to see a link to the ggircs_app in my dashboard, so that I can easily navigate to the fuel management page

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2072]
#### Description:

There are some new fuel management features that are being added to the ggircs-app. These features are mostly for use by CIIP admins & they would like a quick link from their dashboard in CIIP to access these pages.

#### Acceptance Criteria:

Given I am logged in as a CIIP admin
When I navigate to my dashboard
Then I can easily access the ggircs-app fuel type management page via a link

#### Developer checklist

* [ ] The CIIP admin dashboard has a link to the fuel type management page in the ggircs-app
* Meets the DOD

**Comment by LindsayMacfarlane** [comment]
Thank you for walking me through this ticket, much appreciated!
