### ISSUE TITLE
As a CIIP analyst/admin, I want the units for Sold Electricity in Gwh instead of Mwh, so that the units are accurate

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2074]
#### Description:

Sold Electricity has the wrong units attached to the product. They are currently in Mwh & should be in Gwh. Changing the units for the existing product requires making some adjustments to any applications already submitted that have reported this product. This includes:
Total Records: **136**
Final Submitted Records: **67**
Total Records where amount > 0: **49**
Final submissions where amount > 0: **23**

These legacy records will need to have the reported amount for Sold Electricity adjusted by a factor of 1000 to be accurate after the unit change. We will need robust tests to ensure this is done accurately and no other records are affected.

#### Development Checklist:
* [x] The units for Sold Electricity in schema/data/prod/energy_product.sql are in Gwh
* [x] A sqitch change updates the json form_result column in the form_result table for all production form_results that reported this product (divide the amount by 1000)
* Meets the DOD

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/2074?planning-poker) with ZenHub @BCerki @gurjmatharu @matthieu-foucault @pbastia

**Comment by dleard** [comment]
I was thinking about a testing strategy for this. I think it will be a combination automated testing in the code and manual testing in the test environment.

A pgTap test can create a function that does the same thing as the migration. We can create a set of dummy data with form_results that contain sold electricity and some that don't, then run the function to assert that only the proper records are changed & the changes made were done accurately.

I would also like to retrieve all the application/form_result IDs from metabase that contain this product in the TEST environment & run the function there, with a quick edit to the function to include a check that it only changed data for those records. I'd also like to download the carbon tax / incentive data for these applications before running the function and comparing the results after running the function to see if anything odd happens to the calculations after the change.

**Comment by matthieu-foucault** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/2074?planning-poker) with ZenHub @mikevespi

**Comment by dleard** [comment]
Running the migration itself with `\i` creates a nested transaction. Since the pgTap test is a transaction with `begin...rollback` and the migration is a transaction with `begin...commit` then the changes made when setting up the tests are committed because of the `commit` inside the migration, breaking the transactionality of the pgTap unit test.

**Comment by dleard** [comment]
@LindsayMacfarlane 
The only thing you're able to test in dev is that the units changed for Sold Electrcity. We can take a look at test together once this change has made it to that environment.
To check the units you can go to metabase (dev instance) & look at the product table. Sold Electricity's units should now be in GWh

**Comment by LindsayMacfarlane** [comment]
As always, thanks for the demo @dleard !
