### ISSUE TITLE
As a CIIP industrial reporter, I want to see updated wording on the landing page, so that I have the confidence that I will apply for the right program and the right year

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ciip-portal#2083]
#### Description:

Updated wording for the 2022 CIIP round of applications

#### Acceptance Criteria:

Given I am a CIIP industrial reporter
When I visit https://ciip.gov.bc.ca
Then I can see updated wording for the 2022 round of applications

Wording: TBD

#### Dev checklist
- [ ] wording updated in the landing page
- [ ] meets the DOD

**Comment by LindsayMacfarlane** [comment]
Although this was not identified during our prioritization sessions with CIIP staff, I have added to the CIIP 2021/22 Medium Priority EPIC for our own tracking purposes.

**Comment by hannavovk** [comment]
Suggested wording:
"In 2022, CIIP applications will be accepted from May 24 to June 30. 
Outside of this period, you may still log in to view your submitted CIIP applications and submit any changes requested by the Climate Action Secretariat."

**Comment by pbastia** [comment]
@LindsayMacfarlane to test this in -dev:
- login either with your IDIR, or with the test admin login,
- go to 'Reporting Periods',
- edit the 2022 year's dates to not be the entire year
- logout and refresh the landing page

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia - I think I might be having some user error as I updated the dates and refreshed, but the landing page doesn't seem to be reporting the correct dates...nor the message that Hanna requested. If you have time, can you walk me through?

**Comment by LindsayMacfarlane** [comment]
Thank you for walking me through things @pbastia - that was super helpful! Also thank you for creating tickets to capture future work and the bug.
