### ISSUE TITLE
[CIIP 2023] Application Close Time is being set 12 hours early [8]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2096]
Describe the Bug:

The timestamp for "close" times when setting data for the reportingYear table is being set to 11:59am rather than 11:59pm. The expected behaviour is that when setting a close date, it would close at the end of the day.

This should be a simple fix:

The issue originates in [ReportingYearFormDialog](https://github.com/bcgov/cas-ciip-portal/blob/develop/app/containers/Admin/ReportingYear/NewReportingYearFormDialog.tsx#L35) && [ReportingYearFormDialog](https://github.com/bcgov/cas-ciip-portal/blob/develop/app/containers/Admin/ReportingYear/ReportingYearFormDialog.tsx#L56). We are ensuring a full timestamp before sending data to the server, but the `endOfDay` timestamp is set to `hour: 11` where it should be `hour: 23`.

Probability (1-5): 5 - This will happen when editing/creating any "close" time columns on the reporting_year table

Effect (1-5): 3 - Close dates will close 12 hours earlier than expected, it can be mitigated by moving the close date ahead by a day.

Steps to reproduce the behaviour:

Create or edit a reporting year's application_close_time data. In the database you'll see a timestamp of noon that day.

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! I went in to test and could change the reporting period, but didn't see the time stamp? Is that just in the backend? I might just be looking in the wrong spot?

**Comment by BCerki** [comment]
@LindsayMacfarlane, I think the way to test this is to change a reporting application's close time to a day in the future. Then on that day, anytime after 11:59am and before midnight, check that the application is still open. @dleard, is there a better/faster way to test this?

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki - @dleard walked me through.
