### ISSUE TITLE
Migrate to keycloak common realm in the gold cluster (CIIP)

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ciip-portal#2103]
There are a few things we need to do:

- change the user sub type from uuid to text, to support multiple providers
- determine how the migration of existing users will go:
    - for internal users
    - for external users
    If we are doing this, it needs to be done both in the app (update the user records) and in the realm configuration (CSS app)
    
- consider building a special "login page" or components, similarly to CCBC, since "login with IDIR" and "login with bceid" will be 2 different buttons now (see [code](https://github.com/bcgov/CONN-CCBC-portal/blob/211206ef14b94328d43a946969f456944def28e5/app/pages/applicantportal/index.tsx#L148))

**Comment by pbastia** [comment]
To determine with business area:
- Potential outage / contact and how to request a past application (prepare the text changes and a release) 
- Instructions for BCeID registration

**Comment by pbastia** [comment]
#2138 will be addressed as part of this card

**Comment by LindsayMacfarlane** [comment]
This is complete and now in PROD - correct @pbastia?

**Comment by pbastia** [comment]
Correct!
