### ISSUE TITLE
CIIP 2022-23 Enhancement Priorities

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-ciip-portal#2107]
#### Describe the task
Reach out to CIIP team to start conversation around 2022-23 system enhancements.

#### Acceptance Criteria

- [x] Organize ZenHub tickets off the following repositories: ciip-portal, ggircs-metabase, ggircs. (Diana will confirm) in the new ZenHub workspace. Scrum Team will also need to go in to check.
- [x] Review with Dev team to see what their priorities are for enhancements
- [x] Confirm with PO about capacity and timeline of when this work
- [x] Provide CIIP team with a list of known enhancements/requests: CIIP Internal Users will need to be able to go in to that ZenHub workspace to look at each card and determine if it is still needed. 
- [x] Create additional tickets to capture 1) prepare for prioritization session and 2) hold prioritization session

#### Additional context

- miro board used: CIIP Feature Planning - 2021-2022

**Comment by LindsayMacfarlane** [comment]
@Dianadec - are you able to help export a list of ciip and ggircs tickets from ZenHub?

**Comment by Dianadec** [comment]
Looking into it!

**Comment by Dianadec** [comment]
Might need a dev's help with this. It's not a seamless export from what I saw. Alternatively, we can go through ZenHub with them with the filters applied.

**Comment by suhafa** [comment]
@Dianadec Hi Diana! Could we confirm if the repos mentioned in the action item are the one's that capture CIIP related work?

**Comment by Dianadec** [comment]
@dleard @pbastia @LindsayMacfarlane can you confirm that the only repositories we need to look at to review potential ciip enhancements are from the cas-ciip-portal? or should cas-ggircs also be included?

**Comment by pbastia** [comment]
@Dianadec cas-ggircs should also be included (this is where the SWRS ETL happens)

**Comment by suhafa** [comment]
@pbastia @Dianadec Thanks for confirming Pierre and Diana! In that case we are on the right track ![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/bafd9337-3fc0-4022-80ed-dec25ec11d72)

**Comment by LindsayMacfarlane** [comment]
In relation to the capacity and timeline:
- the 2023 CIIP call will open May 23, 2023 (typical process is the Tuesday a week before May 31).
- Priority enhancements would need to be completed prior to that date (I believe last year we tried to wrap things up the month(ish) before in order to leave time for testing, etc.
- In terms of team capacity, that will depend on a few things: the number of enhancements being requested, the priority of those enhancements (i.e., we should only be focusing on the must do items knowing there are a lot of upcoming changes), our other priorities. Prior to these sessions, I don't typically commit or promise anything given we have a lot of priorities :) 

It would be great if we could facilitate the prioritization session before the winter holiday break. We have our Q4 Release Planning session in the first week or two of Jan, so if we have the CIIP priorities in time for that, then we can better prioritize our time in the next 3 months.

**Comment by suhafa** [comment]
@LindsayMacfarlane thank you for noting down this key information Lindsay! 
Some next steps/deliverables are - an Excel sheet with the finalized user stories, emailing out to the CIIP team with the sheet and dates/deadlines, and finally creating tickets to capture prioritization workshop efforts

**Comment by suhafa** [comment]
Deadline for the Prioritization file to be shared back by the CIIP Team - 2nd December
Reminder email will be sent on the 30th of November
Need to set up future meeting requests for prioritization sessions (to be captured in new tickets)

**Comment by suhafa** [comment]
New tickets created #1207 #1208
@LindsayMacfarlane this ticket is good to be closed! Thank you as well as @Dianadec for all your support with this task!

**Comment by LindsayMacfarlane** [comment]
Thank you @suhafa. Can we pull in the planning ticket into the 'next sprint' column for our sprint planning session this morning.
