### ISSUE TITLE
CIIP Features for 2022/2023

### ISSUE THREAD

**Issue by rdromey** [bcgov/cas-ciip-portal#2109]
This Epic will capture user stories related to the requested features for CIIP Enhancement Planning.

From Lindsay's note in miro: This epic is capturing the discussions/scoping of potential work...but not the design/development work.

**Comment by Dianadec** [comment]
@LindsayMacfarlane Could we prioritize the cards currently in the Backlog that are part of this Epic? Most have low priority labels. But, perhaps out of those, we can determine which ones you might like to see pulled into upcoming sprints, and refine those ones first.

**Comment by LindsayMacfarlane** [comment]
Thanks @Dianadec - the high priority CIIP 2022-23 are already pulled into 'next sprint backlog' for the teams review/consideration.

**Comment by hannavovk** [comment]
@Dianadec @rdromey @pbastia I think for this Epic we should move any outstanding cards to the icebox and close the ticket. If everyone agrees, can one of the SMs do that please? Thanks!

**Comment by rdromey** [comment]
Uncompleted tickets removed and added to the FY 2023/2024 Epic.
