### ISSUE TITLE
Metabase Training Dev Preparation

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#2111]
In preparation for the training sessions in November, we'll need prepare the following:

- Review Miro Board content 
- Setup Metabase if/as needed
- Update screenshots if we update metabase to the new version.
- schedule dress rehearsal with scrum team (dry-run)

Internal Facilitator document: https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EUiQefstINZIkf6jKqKgmz4BENT4V3S5i2yDMUR9vqg04g

**Comment by Dianadec** [comment]
@dleard @pbastia How about scheduling the dry-run with the team on Monday, Nov. 20? The actual session is on Tues, Nov. 21.

**Comment by dleard** [comment]
Could we possibly do it Friday? Doing the dev dry run session the day before doesn't leave us much time if we discover anything that we'd like to change / update.

**Comment by Dianadec** [comment]
I will email the attendees on Monday as a reminder and to ensure that they all have access.

**Comment by LindsayMacfarlane** [comment]
Moving this ticket to PO review column as complete.

**Comment by LindsayMacfarlane** [comment]
Great work @pbastia and team! The training was successful. There were a lot of really great questions in the breakout room I attend.
