### ISSUE TITLE
Conduct prioritization session and post-workshop tasks

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-ciip-portal#2120]
#### Describe the task
Following preparation work done in #2107, we need to conduct the prioritization session

#### Acceptance Criteria
- [x] Touch base with Lindsay to review the workshop plan
- [x] Conduct workshop (invite sent for the 13th of December 2022)
- [x] Compile learnings from workshop (#2107)
- [x] Share findings with team for future planning
- [x] Collectively decide what to work on
- [x] Document final decision
- [ ] Update CIIP team with final decision (WILL BE DONE AT SPRINT REVIEW)
- [x] Update Zenhub tickets accordingly (=action)

#### Additional context

- [Workshop Miro Board](https://miro.com/app/board/o9J_llLjTeI=/)
- Or here

**Comment by suhafa** [comment]
Meeting with CIIp was conducted. The CIIP and Scrum team went over tickets indicated to be High and some Medium priority ones. Some takeaways:
- CIIP team indicated that they are interested in Metabase training on Dashboards (creating, updating etc) 
- The Scrum Team will evaluate the estimated work further on
- We can go over the remaining medium and low priority items in the subsequent months

**Comment by suhafa** [comment]
@LindsayMacfarlane - this ticket is good to be closed. Just have two questions blocking me here:
1) Do I remove the prioritized tickets from CAS Zenhub board's Icebox? Which pipeline do we stack them under?
2) Part of the AC for this was to inform CIIP, we could communicate these steps taken in a Sprint Review I think. What do you say?

**Comment by LindsayMacfarlane** [comment]
Thank you so much for all your work and effort on this task @suhafa! You did a fantastic job facilitating and sparking good conversation. To answer your questions:

- Do I remove the prioritized tickets from CAS Zenhub board's Icebox? Which pipeline do we stack them under? Yes please and you can move them into the backlog column. We'll probably want to make sure they have a 'backlog refinement' label on them as well. 

- Part of the AC for this was to inform CIIP, we could communicate these steps taken in a Sprint Review I think. What do you say? Updating at the sprint review is a great idea. In terms of next steps for the team in January: reviewing priority items and refining to prep for development, reaching out to CIIP team when we have questions or require updated data to put into the system, gradually pulling in work over the next few months to ensure implementation in time for the CIIP call opening :)
