### ISSUE TITLE
Prepare for prioritization session

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-ciip-portal#2121]
#### Describe the task

Groundwork for prioritization session with the CIIP team for enhancements work planning

#### Acceptance Criteria

- [x]  Nudge CIIP team to review icebox items
- [x]  Diana/Lindsay to set up meeting times for discussion
- [x]  Design workshop (CIIP Feature Planning - Miro Board) to rank items based on value & feasibility
- [x] Consult with Jaimie on how to best conduct prioritization workshops 
- [x] Update Miro board after receiving [finalized file](https://bcgov.sharepoint.com/:x:/r/teams/00608-CIIPAnalysts-DevTeamFeedback/Shared%20Documents/CIIP%20Analysts%20-%20Dev%20Team%20Feedback/CIIP%20Enhancements_Dec%202022%20(Received%20by%20CIIP%20team).xlsx?d=wafc4159ae35a4ae69c226014a015ef1b&csf=1&web=1&e=lBU1Yk) from CIIP team
- [x]  Notify Scrum team about the session, and decide who will be attending it from the team (invite sent)
#### Additional context

- Building on work done in #2107

**Comment by suhafa** [comment]
@LindsayMacfarlane this ticket is good to be closed after your review Lindsay! I can sync the game plan for the session with you in our check-in on Monday.

**Comment by LindsayMacfarlane** [comment]
Thank you @suhafa! I'm looking forward to this session :)
