### ISSUE TITLE
The validation warning regarding not having a fuel reported for each emission category is being shown when it shouldn't

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2125]
The validation warning regarding not having a fuel reported for each emission category is sometimes being shown to both reporters & analysts when it shouldn't. 

Probability (1-5): 2

Effect (1-5): 3

Steps to reproduce the behaviour:

- Behzad will be sending us some details on which applications are being affected so that we can reproduce the behaviour.

**Comment by LindsayMacfarlane** [comment]
Updated priority based on reviewing prioritization session. Pulling into backlog so that it is tackled.

**Comment by LindsayMacfarlane** [comment]
Followed up with program area through the CIIP Internal Users Channel on January 30, 2023 for examples of the bug.

**Comment by Dianadec** [comment]
Added high priority label based on Dylan's feedback that this should be done before next ciip cycle.

**Comment by Dianadec** [comment]
Need to add info in from CIIP internal users channel - B's response.

**Comment by pbastia** [comment]
Info from BB:
> [03-09 9:55 a.m.] 
    When fugitive emissions are reported, but no fuel is reported with the emissions category of fugitive, we see a warning. This should be corrected. applicants are not supposed to report fuel usage with the emissions category of fugitives, because it is not a useful fuel usage. Example application ID 1846. Please be in contact with KZ or CW if you needed more information for fixing this problem. Thank you!

**Comment by dleard** [comment]
This may not be a bug. The example application with ID 1846 is also missing a reported fuel for venting. I've read the function's code & tested locally. If the only emission category missing a fuel was fugitive, then the validation error would not show. I've reached out in our internal CIIP channel to KZ & CW to confirm if our validation check is working as expected or if the issue is not with fugitive emissions.

**Comment by dleard** [comment]
@pbastia Closing this as it is not a bug. CAS confirmed in our internal channel that the way it is working now is the way it should work.
