### ISSUE TITLE
As a Reporter, I want to attach a file to my application, so that I can submit production verification statements

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-ciip-portal#2126]
#### Description:
Issue was identified in [CIIP Enhancements Prioritization](https://miro.com/app/board/o9J_llLjTeI=/) planning. Context from the session from notes taken by attendees:

"Files will be stored on google cloud storage. CIIP app will contain the metadata related to the file. They want the ability to just download, not upload. Can users delete the file if wrong? (Note: we don't delete). Will need requirements gathering/UI design to better understand what is needed."

There is a matching analyst/download user story: #2181

#### Acceptance Criteria:

Given I am an industrial reporter
When I am filling out an application
And I am on the "production" tab
Then I can see an optional file upload widget

Given I am an industrial reporter
When I am on the "production" tab
Then I can upload multiple documents

Given I am an industrial reporter
When I am on the "production" tab
And I uploaded one or more documents
Then I can remove these documents from my application version by clicking a delete button

#### Dev checklist:
- [x] replicate the exact same pattern as done in CIF
- [x] attachment table
- [x] postgraphile similar to CIF: https://github.com/bcgov/cas-cif/blob/develop/app/server/middleware/graphql/uploadFieldPlugin.js
- [x] provisioning buckets for attachments like [in cif](https://github.com/bcgov/cas-cif/blob/fe6840001fa9c893f56ec117230e93ba70851c1f/chart/cas-cif/templates/bucket-provisioning-job.yaml#L45)
- [x] upload component [in cif](https://github.com/bcgov/cas-cif/blob/develop/app/pages/cif/project-revision/%5BprojectRevision%5D/attachments.tsx)

#### Wireframe
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/8fd4bc16-05d6-4a4b-ac56-812ab3c0e4eb)

**Comment by LindsayMacfarlane** [comment]
Updated priority to Medium based on prioritization session.

**Comment by Dianadec** [comment]
Need to determine if this is getting iceboxed. To do: discuss with CIIP team @LindsayMacfarlane @pbastia

**Comment by pbastia** [comment]
The question is - how much value would this feature bring, in regard to the high cost of implementation? Especially given that verification statements are already uploaded to SWRS and retrievable through Metabase.

Maybe a direct link to the right Metabase query to see these attachments could be a good candidate, and would get us close to the required functionality? @LindsayMacfarlane @Dianadec

**Comment by pbastia** [comment]
Answer:
- This is a new requirement for 2022 tax year
- The verification statement is different from the one submitted in SWRS
- It's more than a 'nice to have' and will avoid the ciip team to handle email communication separately for applications requiring that statement uploaded

**Comment by pbastia** [comment]
Answer:
- This is a new requirement for 2022 tax year
- The verification statement is different from the one submitted in SWRS
- It's more than a 'nice to have' and will avoid the ciip team to handle email communication separately for applications requiring that statement uploaded

**Comment by pbastia** [comment]
There could be a few ways of doing this:
- a field on an existing form (maybe products? if it's a production verification statement)
- an extra step in the wizard
- a field just before submitting the application, on the summary form

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/2126?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by Sepehr-Sobhani** [comment]
Do we have an attachment table to keep the file info or it's part of this card?!

**Comment by mikevespi** [comment]
Given these are proponents documents, we are hard deleting correct?

**Comment by BCerki** [comment]
@suhafa, do you have more information on who's allowed to access/delete these attachments? I assume industry users can do everything including hard delete (correct me if I'm wrong). What are analysts and administrators allowed to do?

**Comment by suhafa** [comment]
@BCerki I don't have any information on what analysts and admin can do here, tagging @pbastia for any insight he may have for this

**Comment by BCerki** [comment]
Note on upload middleware: https://github.com/relay-tools/react-relay-network-modern/issues/109

**Comment by pbastia** [comment]
Thanks for the hard work @BCerki ! When I try to upload multiple different attachments, I get the "Oops! ..." message, even if it's not the same file. Is there something I might be doing wrong?

**Comment by BCerki** [comment]
@pbastia, it's because of a unique index, I added it to this card: https://github.com/bcgov/cas-ciip-portal/issues/2196

**Comment by pbastia** [comment]
Thank you @BCerki ! I'll mark this one as completed then :)
