### ISSUE TITLE
Link to Metabase on CIIP application dashboard is broken.

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-ciip-portal#2127]
#### Describe the task
This card has two sides: updating and managing certificates. Can be split into two. Scrum team suggested we incorporate certbot to get URL back

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by Dianadec** [comment]
This has been fixed.
