### ISSUE TITLE
Plan Metabase training session on Dashboards

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-ciip-portal#2129]
#### Describe the task
Teams want to learn how to manage, create, maintain etc. dashboards in Metabase. 

#### Acceptance Criteria

- [ ] Create Miro Board content
- [ ] Setup Metabase if/as needed
- [ ] Update screenshots if we update Metabase to the new version.
- [ ] schedule rehearsal with scrum team 

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by rdromey** [comment]
Probable duplicate in wrong repo.
