### ISSUE TITLE
Task: Setting up BCeID for CIIP

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-ciip-portal#2130]
#### Describe the task
We need to set up the ability for applicants to use BCeID. We will need to work with the IDIM team to get set up. 

#### Acceptance Criteria

- [x] submit intake form
- [x] complete kickoff meeting
- [x] discuss potential impacts and workflow solutions with CIIP team
- [x] complete additional paper work
- [ ] Get online service directories from BCeID client manager

#### Additional context

* What communication needs to go out to IRC and how to communicate to users?
* From a technical perspective, it won't change much. The BCeID users will have an id like 1234567890@bceid when our idir users have 1234567890@idir. Once they're authenticated, there's nothing different

**Comment by pbastia** [comment]
In order to use BCeID, we need the team to be onboarded officially.
we'll need to setup a meeting with the IDIM team early in the new year to move forward

**Comment by pbastia** [comment]
This does not block #2103, but we'll beed to communicate with the CIIP program:
- What losing the username/password authentication for external users will mean - and how will this be communicated to them
- Have a way for them to retrieve past applications even though the current CIIP window is closed (maybe a manual process?)

cc @LindsayMacfarlane

**Comment by pbastia** [comment]
Working document: https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EehMATiy3L1CscuxHEdNwO8BGsbdYUHJQ_TGDC7CGz755g?e=8JgnSU

**Comment by LindsayMacfarlane** [comment]
@dleard - the email I have is that our client manager has added the unpublished PROD-OSD entry. No link was provided in the email. What else do we need? Or is this ticket now complete?

**Comment by dleard** [comment]
Can you forward me the email? We should be close to done with this, but we still need to implement the login option in CIIP (which should be short & I think Pierre started on it)

**Comment by LindsayMacfarlane** [comment]
@dleard - we now have our online service directories...correct? Can this ticket be closed?

**Comment by dleard** [comment]
Yes, this one and #2134 can be closed, they are _sort of _ duplicates? I checked this morning and we have been approved to use BCeID in CIIP prod
