### ISSUE TITLE
CIIP Security Audit

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ciip-portal#2131]
#### Describe the task
Auditing security 

#### Acceptance Criteria

- [ ] make sure all service accounts are only used in one place
- [ ] schedule secrets rotation
- [ ] ...

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by LindsayMacfarlane** [comment]
@pbastia @dleard  - based on your email, I believe this ticket can be closed. Thank you!

**Comment by pbastia** [comment]
Work has been carried out
