### ISSUE TITLE
As a CIIP developer, I want to be approved to use BCeID in a production environment, so that external users can use it to log in with CIIP

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ciip-portal#2134]
#### Description:

There is a certain amount of administrative work to be carried out in order to use BCeID in a production environment
(see "Next Steps: CIIP | GGIRCS integration" email from Jan 4)

#### Acceptance Criteria:

Given I am a CIIP developer
When I setup keycloak gold in prod
Then BCeID is available as a login option

#### Development Checklist:
- [ ]

**Comment by LindsayMacfarlane** [comment]
Currently being blocked. Need to do some follow up with IDIM team.

**Comment by dleard** [comment]
Closing. BCeID is now an auth option for CIIP prod in our KC gold
