### ISSUE TITLE
Work with Tammy on BCeID messaging/communication

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-ciip-portal#2136]
#### Describe the task
We will need to communicate to our CIIP industrial operators regarding the migration to BCeID and potential impacts. 

#### Acceptance Criteria

- [x] Get Tammie drafts/communication used by previous teams
- [x] Work with Tammy on draft communication
- [x] Get IDIM to review communication

#### Additional context

* Tammie to send out communication on January 27th

**Comment by pbastia** [comment]
Moving to In Progress as this is ongoing.

**Comment by LindsayMacfarlane** [comment]
Communication sent out. A copy of the email will be uploaded to our scrum team channel CIIP>BCeID documentation.
