### ISSUE TITLE
As a CIIP user, I shouldn't be able to change my email address, because it will be retrieved from the OAuth credentials

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ciip-portal#2138]
#### Description:

on the `UserForm` component, we update the email address, this should be pre-populated initially from the credentials, and later from the database.

#### Acceptance Criteria:

Given I am a CIIP user
When I login for the first time
Then I cannot change my email address on the registration form

Given I am a CIIP user
When I select my user profile from the top right menu
Then I cannot change my email address on the form

**Comment by pbastia** [comment]
This was actually part of the Keycloak migration #2103

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - is there anything I need to test for this one?

**Comment by pbastia** [comment]
Log in to ciip-dev and verify that the email is read-only. I can walk you through it

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia - tested in dev and ticket meets acceptance criteria. Thank you for your work on this issue :)
