### ISSUE TITLE
As a CIIP admin, I want CTA incremental tax basline data to be entered for 2022, so that incentives can be calculated by the app

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2139]
#### Description:
This is a replacement card for #2048. The work defined there was intended to be a UI that could be used by CAS admins to set this data. We have decided not to implement this UI, which means we will need to update the data in our tables manually. This should only be ~20 rows of data to enter.

For this work we need to get the new set of carbon tax data from CAS & enter it into our `incremental_fuel_charge_baseline` table manually. This table has a foreign key that relates to the `carbon_tax_act_fuel_type` table which defines each carbon taxed fuel. There shouldn't be any changes to that table, so all of the work needed to be done here should only be in  `incremental_fuel_charge_baseline`.

The incentive calculation uses a baseline value from the `incremental_fuel_charge_baseline` table that aligns with the federal rates. The table has this shape:

` id integer,
  carbon_tax_act_fuel_type_id integer,
  start_reporting_period integer,
  end_reporting_period integer,
  fuel_charge_baseline numeric,
  comment varchar(100000)`

#### Acceptance Criteria:
- [ ] get the new carbon tax baseline data from CAS
- [ ] update  `incremental_fuel_charge_baseline` with the new values
- [ ] ensure accuracy of the entered data

#### Notes:
- Rates can be found in our [MS Teams Channel](https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/ERAfpmMkmXFNhsQ4IiRJvokBG_O2VLZ9MoVZas7EQb4hww?e=u7OJET)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/2139?planning-poker) with Zenhub @BCerki @gurjmatharu @mikevespi @pbastia @sam-warren @tmastrom @Sepehr-Sobhani

**Comment by Dianadec** [comment]
Added business area tag to contact B.B.

**Comment by LindsayMacfarlane** [comment]
Messaged program area on January 19 through the CIIP internal users channel.

**Comment by LindsayMacfarlane** [comment]
Program area provided rates. Spreadsheet stored in Scrum Team Channel, in [CIIP folder](https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/ERAfpmMkmXFNhsQ4IiRJvokBG_O2VLZ9MoVZas7EQb4hww?e=u7OJET) (file called 2022 CT rates)

**Comment by dleard** [comment]
@LindsayMacfarlane After reviewing the baseline data provided by CAS, we've determined that there are no changes to the baseline rates for this year. This means that no work is needed on our part as our system is already set up to use the current baselines until there is a change. I suggest dropping this card's point value to a 1 to account for the exploration and move it to closed. Thanks @BCerki for the initial investigation on this.

**Comment by LindsayMacfarlane** [comment]
Thank you so much @BCerki for your investigative work and noticing that no changes are required. Thank you @dleard for reaching out to the program area to get confirmation and make the above recommendation. Much appreciated :)
