### ISSUE TITLE
As a CIIP Admin, I want fuels to be associated to emission categories, so that there is less margin for error when reporters are reporting fuels

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2145]
#### Description:
Applicants should report flaring and venting using the Natural Gas fuel. The guidance states this, but it was ignored by many and we received many applications with various other fuels reporting under flaring and venting.

This is a replacement card for #1985. The previous card outlined the creation of a UI for CIIP admins to be able to associate fuels to emission categories themselves, but given timelines we have instead decided to do this manually as a dev team.

We should get the list of fuels and their associated emission categories from CAS, then create and populate the necessary tables ourselves.

#### Acceptance Criteria:
- A fuel_emission_category table exists. This table has a the data structure {id, fuel_id, emission_category_id} plus the timestamp columns generated by the upsert_timestamp_columns function.
- The fuel_emission_category table has select, insert and update permissions for admins, and select for reporters and analysts.
- The fuel_emission_category table is populated with the fuel-emission category relationship data as provided by CAS
- Tests

**Comment by LindsayMacfarlane** [comment]
@dleard - can this ticket be estimated prior to us getting the list?

**Comment by dleard** [comment]
yes, similar to the CTA incremental tax work this should be a minimal amount of data entry work

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/2145?planning-poker) with Zenhub @BCerki @gurjmatharu @mikevespi @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by LindsayMacfarlane** [comment]
Program area has provided fuels_emissions category. File can be found in Scrum Team>Files>CIIP. Direct link: https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EfgHZU1baH5GriNNwlZl64cBUs02NOUn_FWS0Fx69zX_ww?e=zoNYB7

**Comment by Dianadec** [comment]
@gurjmatharu @tmastrom please add your estimates if you would like to.

**Comment by Dianadec** [comment]
@LindsayMacfarlane can the business area tag be removed now that we have that file?

**Comment by LindsayMacfarlane** [comment]
Hi @tmastrom - please add your estimate :)

**Comment by Dianadec** [comment]
Opportunity for new CIIP people to try this card.

**Comment by BCerki** [comment]
Nothing to see on this one, Lindsay

**Comment by LindsayMacfarlane** [comment]
Thanks for your work on this @BCerki! Moving to the accepted column :)
