### ISSUE TITLE
Bug: CIIP logout button is missing on the "pending analyst" page [8]

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ciip-portal#2149]
Describe the Bug:

When I login with my IDIR and I haven't been granted a role in the realm - which will happen all the time after the KC Gold migration - then I am on a "pending approval" page. Except that logging out isn't an option, so the session roles are still empty until we let the session expires.

Probability (1-5):4
Effect (1-5):4

Steps to reproduce the behaviour:
Login for the first time (to ciip-dev or test) with no role in the shared realm
Add the roles or have someone else add them
Then no action is possible to logout and re-open a session with the right roles

## Dev Checklist
`Header.tsx` uses the `ciipUserBySub` value to determine if a user is registered and display the dropdown with a logout button. This will be `null` when a user is logging in for the first time (their sub hasn't been updated to the KC gold one yet).
- [x] extract the logout form to display it instead of the profile dropdown (`Header.tsx:L120`)

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/719cc3ea-0802-4ba5-85c0-8c113e1c2248)

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Tested in dev by first removing my permissions in our common hosted single sign-on for CIIP. I was able to confirm that when I got the 'approval required' ui that I now see a logout button in the top right. Thanks!
