### ISSUE TITLE
Metabase training: 1 on 1 dashboard training

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2151]
A memeber of CAS expressed interest after our Metabase training in becoming fluent in Metabase dashboards. They would like to be able to create / update dashboards similar to the validation dashboard we created for CAS.

Todo:
Provide a 1 on 1 training session with on dashboards

**Comment by LindsayMacfarlane** [comment]
Dylan has reached out to schedule time.
