### ISSUE TITLE
PR Review Process updates

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#2159]
Review Process - Summary: what came out of the PR Review Process meeting on Feb 2.

- A new pipeline has been added in Zenhub called "Review in Progress"
	
- Before moving a card from "Review in Progress" to "Pending PO Approval", check shipit first to ensure that it is in dev.
	
- Good practice is once you've finished working on a card, check if anything needs to be reviewed before pulling a new card into the sprint
	
AC:
  - [x] Updates to the written PR Review process to be added to the cas-home documentation on github. 
	
Check out the team process miro board for more tidbits on what we discussed

**Comment by pbastia** [comment]
@LindsayMacfarlane  @Dianadec  the document can be viewed here: https://github.com/bcgov/cas-home/blob/main/docs/version_control/pull-request-review-process.md

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani - this is fantastic and will be really helpful for team members to learn and understand our pr review process. Much appreciated!
