### ISSUE TITLE
MS Teams Documentation Updates

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#2176]
#### Describe the task
Updating information relevant to the team on MS teams as a priority related to onboarding new staff.

#### Acceptance Criteria

- [x] Transfer information out of the Wiki app in Scrum Team into OneNote as a new tab
- [x] Update links in the Scrum Team One Note
- [x] Transfer information out of the Wiki app in General into another app (looking into sharepoint as a tab - nicer to view, easy to add and update).
- [x] Update Miro boards:
- [x] Onboarding Miro Board
- [x] Team Process Miro Board: summarize current team processes in a format that can also be used as a ppt slideshow.
- [x] gather team feedback about onboarding experience
- [x] check in with team about access issues (internal vs. guest accounts)
- [ ] Create additional task cards if needed, related to the documentation frame in the Team Process Miro board (based on team feedback on the topic of documentation).

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by Dianadec** [comment]
@LindsayMacfarlane I added this as a task for more transparency and to capture some of the pieces of this little project. I needed a checklist :D

**Comment by Dianadec** [comment]
Just need to continue on the documentation miro sticky notes, but that will be an ongoing task.

**Comment by LindsayMacfarlane** [comment]
Thank you @Dianadec! This is a big task and will benefit the team greatly :)
