### ISSUE TITLE
Work Style Profiles Team Activity

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#2177]
#### Describe the task
Based on cognitive diversity coaching Diana is taking, this activity is meant to: 
Learn about differences among the team which will lead to supporting collaboration and working together, while making an intentional effort to support others with what they need. This will lead to increased safety and sense of inclusion for the team, which will provide flexibility and customization on how we work, organize idea-sharing to bring everyone's best ideas and fuse them into innovative solutions. :)

#### Acceptance Criteria

- [x] Setup 30 mins overview meeting with the team
- [x] async work during the sprint
- [x] Setup 60 mins debrief meeting with team at the end of the sprint

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by LindsayMacfarlane** [comment]
I love this activity @Dianadec ! I can't wait to hear about the results (and perhaps use this with new teams :) )
