### ISSUE TITLE
Update CIIP Demo Video on YouTube

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#2188]
#### Describe the task
The video is out of date with the process to register. Need to contact Robb to determine who needs to edit it.

https://www.youtube.com/watch?v=sh5y42ahhEE

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by pbastia** [comment]
This is outside of the scope of what this team does

**Comment by pbastia** [comment]
Closing, as this is outside of the scope of the DST
