### ISSUE TITLE
CIIP Production view in metabase is missing values for Product Name

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2192]
Many rows in the CIIP Production view in metabase are missing the `Product Name` field. This is because, when selecting a product as a reporter, the name is not saved to the `form_result` and the CIIP Production view pulls the (non-existent) product name from that `form_result` data.

We always have the `product_id` saved in the `form_result`, so having the name saved there too is redundant. The fix here is:
- Update the `ciip_production` view to populate its `product_name` field by retrieving it from the `product` table via the `product_id` foreign key

Probability (1-5): 4
The view will have blank product_name fields for any products selected via the dropdown by the reporter

Effect (1-5): 2
There is a work-around in metabase that has been shared in CIIP Internal

Steps to reproduce the behaviour:
- Look in metabase and filter by Product Name is empty.
- See lots of results wth no Product Name in the view

**Comment by dleard** [comment]
@pbastia The bug occurred when a product was reported by selecting it from the dropdown. So to test this fix:
- log into CIIP as a reporter
- create an application and add a product in the production tab
* only a couple naics codes allow entering products. I know `111419 - Food Crops Grown Under Cover` has products associated to it that can be entered
- submit the application
- look in metabase dev and see if the product_name field shows a value

**Comment by pbastia** [comment]
@dleard I went through this, and the product_name field is empty in MB...maybe we can have a look together to see if I did something wrong

**Comment by dleard** [comment]
oops, looks like the deployment got stuck on a happo ci failure in shipit, so the fix didn't make it to dev. Deploying now

**Comment by pbastia** [comment]
I can see the product name in metabase. Thank you @dleard !
