### ISSUE TITLE
As a reporter, I want to see the requirements for providing a verification statement, so that I know if I am required to provide one

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2203]
#### Description:
Help text would be helpful on the production tab where the reporter can upload a verification statement.
Here is the copy provided by CAS to be shown in the tooltip:

A production data verification report is required for either:
- a facility that is a Single Facility Operation (SFO) for which verification is required under GGERR, or
- a facility that is part of a Linear Facilities Operation (LFO) if that facility emitted 25,000 tCO2e or more, not including reporting-only emissions, in the current or any of the past three reporting periods

#### Acceptance Criteria:

Given I am a reporter viewing the production tab
When I look at the verification statement upload section
Then I can see the requirements for providing a verification statement

#### Checklist
- [ ] An alert component (variant=info) is shown in the verification statement upload section of the production tab that displays the information on the requirements for providing a verification statement

**Comment by pbastia** [comment]
I can see the alert component with the requirements. Nice work @JoshLarouche !

**Comment by JoshLarouche** [comment]
Thanks!
