### ISSUE TITLE
Load testing in collaboration with Platform Services

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ciip-portal#2204]
Once #2195 is complete, we will need to contact platform services and schedule some time off-hours to perform the load testing.

Todo:
- [x] Contact PS and schedule a time to perform load testing
- [x] Perform the load testing
- [x] Upload results

**Comment by mikevespi** [comment]
Results were uploaded to Scrum Team files in LoadTestingResults/CIIP_2023.

**Comment by pbastia** [comment]
Load testing was conducted successfully! Thanks @mikevespi !
