### ISSUE TITLE
Update PR Review Process Documentation

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#2207]
Add notes from Dev Team agreements on April 26 to the cas-home documentation.
	
AC:
  - [ ] Updates to the written PR Review process to be added to the cas-home documentation on github. 
	
Check out the DevOps Team Agreements miro board for notes to add.

**Comment by Sepehr-Sobhani** [comment]
Link to existing doc: https://github.com/bcgov/cas-home/blob/main/docs/version_control/pull-request-review-process.md

**Comment by pbastia** [comment]
Thank you @BCerki !
