### ISSUE TITLE
2024 call (a year from now): review changes proposed for SWRS

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ciip-portal#2214]
#### Describe the task
QB proposed a few change requests to SWRS
https://bcgov.sharepoint.com/:f:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/GGIRCS/2024_CRs_to_SWRS?csf=1&web=1&e=Jq3xeW

#### Acceptance Criteria

- [x] review proposed change requests
- [x] investigate if the team would need other changes
- [x] send suggestions back to QB

**Comment by dleard** [comment]
No issues with the proposed changes. Closing this issue
