### ISSUE TITLE
is graphql-cli needed?

### ISSUE THREAD

**Issue by wenzowski** [bcgov/cas-ciip-portal#6]
@hamzajaved Given the graphql schema is generated by [Graphile](https://www.graphile.org/) do we need to have `graphql-cli` in the `devDependencies`?

**Comment by wenzowski** [comment]
It introduces a bunch of known vulnerabilities as it doesn't seem to be maintained.

I've tried bumping those deps but it might not work with overrides as-is.
https://github.com/bcgov/cas-ciip-portal/blob/2acb29aef3b4fa0c8e9877ae1652cab923e75778/package.json#L48

**Comment by hamzajaved** [comment]
If it doesn't break anything when we remove it then no, I don't need it. It came with the next-relay package.

**Comment by wenzowski** [comment]
@matthieu-foucault fixed this in #64 🎉
